### ISSUE TITLE
Portfolio changes

### ISSUE THREAD

**Issue by gregthompson27** [AnijahPam/AnijahPam.github.io#1]
https://github.com/AnijahPam/AnijahPam.github.io/blob/2dfde02a46eeec79923e075f3dc7aba303091e48/portfolio.html#L52

@AnijahPam, you're missing a `>` symbol at the very end of this line.

___

https://github.com/AnijahPam/AnijahPam.github.io/blob/2dfde02a46eeec79923e075f3dc7aba303091e48/portfolio.html#L81-L87

The `<ul>` that you've created here is good, but should be in your `content` div. You have a blank `ul` on lines 73-75 that you can replace with the `ul` you have on lines 81-87.

___

https://github.com/AnijahPam/AnijahPam.github.io/blob/2dfde02a46eeec79923e075f3dc7aba303091e48/portfolio.html#L70-L90

Lastly, this entire `<main></main>` section should be right below the closing `</nav>` tag (so it should go in between the closing nav tag and closing div tag)

**Comment by JoshHunter11** [comment]
@gregthompson27 all requested issues have been resolved. However, from lines 84-91, the student has repeated code from their portfolio links and image source. I don't know if it impacts the functionality of the project, but it does make it somewhat confusing to read.
