### ISSUE TITLE
Add class and id attributes

### ISSUE THREAD

**Issue by gregthompson27** [AnijahPam/AnijahPam.github.io#4]
<h3>Feedback for todo 10</h3>

https://github.com/AnijahPam/AnijahPam.github.io/blob/fbcb2276da6463184c981d2dee6add9e662bf2af/index.html#L14-L47

@AnijahPam, Make sure to add the style rules listed in [TODO 10](https://github.com/OperationSpark/first-website-hs#todo-10--add-in-attributes) at throughout your HTML file. You've already completed part 1, you just have to complete parts 2-4 of TODO 10

**Comment by JoshHunter11** [comment]
@gregthompson27 issue resolved
