### ISSUE TITLE
Fix up if/else syntax

### ISSUE THREAD

**Issue by gregthompson27** [AnijahPam/AnijahPam.github.io#5]
<h3>Feedback for todo 7</h3>

https://github.com/AnijahPam/AnijahPam.github.io/blob/f6b52d60832c752d3fa397a921e2c8af629e48ba/projects/bouncing-box/index.html#L105-L112

@AnijahPam, this code overall looks pretty good, there's a couple syntax pieces that you're missing though. First, on line 105, you have a `;` after your condition that is stopping your code from executing. There shouldn't be a semicolon there. Next, else statements don't need conditions inside of parentheses like if statements do. So your code will end up looking somewhat like this:

```js
if (speed > 0) {
    speed = speed + 3;
}
else {
    speed = speed - 3;
}
```

It looks like you still have a line (line 103) that's changing speed. Because of the if/else statement you've written you can remove that line of code.

**Comment by JoshHunter11** [comment]
@gregthompson27 The syntax of the if/else statement has been fixed, but the student still has to delete the code changing the speed on line 103.
